production:
  clients:
    default:
      database: amf_cli
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: amf_cli_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
